-- MySQL Script generated by MySQL Workbench
-- Thu May  6 13:35:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cuide
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuide
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuide` DEFAULT CHARACTER SET utf8 ;
USE `cuide` ;

-- -----------------------------------------------------
-- Table `cuide`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuide`.`cuidador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`cuidador` (
  `cuidador_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `certificacao` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`cuidador_id`),
  INDEX `fk_cuidador_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_cuidador_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `cuide`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuide`.`idoso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`idoso` (
  `idoso_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idoso_id`),
  INDEX `fk_idoso_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_idoso_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `cuide`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuide`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`exame` (
  `exame_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `idoso_idoso_id` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`exame_id`),
  INDEX `fk_exame_idoso1_idx` (`idoso_idoso_id` ASC) ,
  INDEX `fk_exame_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_exame_idoso1`
    FOREIGN KEY (`idoso_idoso_id`)
    REFERENCES `cuide`.`idoso` (`idoso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exame_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `cuide`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuide`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`medicamento` (
  `medicamento_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `dosagem` VARCHAR(45) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `idoso_idoso_id` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`medicamento_id`),
  INDEX `fk_medicamento_idoso1_idx` (`idoso_idoso_id` ASC) ,
  INDEX `fk_medicamento_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_medicamento_idoso1`
    FOREIGN KEY (`idoso_idoso_id`)
    REFERENCES `cuide`.`idoso` (`idoso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `cuide`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuide`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`consulta` (
  `consulta_id` INT NOT NULL AUTO_INCREMENT,
  `medico` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `idoso_idoso_id` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`consulta_id`),
  INDEX `fk_consulta_idoso1_idx` (`idoso_idoso_id` ASC) ,
  INDEX `fk_consulta_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_consulta_idoso1`
    FOREIGN KEY (`idoso_idoso_id`)
    REFERENCES `cuide`.`idoso` (`idoso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `cuide`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuide`.`sintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`sintoma` (
  `sintoma_id` INT NOT NULL AUTO_INCREMENT,
  `alteracoes` TINYINT NOT NULL,
  `local_alteracoes` VARCHAR(45) NOT NULL,
  `local_dores` VARCHAR(45) NOT NULL,
  `observacoes` VARCHAR(255) NOT NULL,
  `idoso_idoso_id` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`sintoma_id`),
  INDEX `fk_sintoma_idoso1_idx` (`idoso_idoso_id` ASC) ,
  INDEX `fk_sintoma_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_sintoma_idoso1`
    FOREIGN KEY (`idoso_idoso_id`)
    REFERENCES `cuide`.`idoso` (`idoso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sintoma_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `cuide`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuide`.`idoso_has_cuidador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuide`.`idoso_has_cuidador` (
  `idoso_idoso_id` INT NOT NULL,
  `cuidador_cuidador_id` INT NOT NULL,
  PRIMARY KEY (`idoso_idoso_id`, `cuidador_cuidador_id`),
  INDEX `fk_idoso_has_cuidador_cuidador1_idx` (`cuidador_cuidador_id` ASC) ,
  INDEX `fk_idoso_has_cuidador_idoso_idx` (`idoso_idoso_id` ASC) ,
  CONSTRAINT `fk_idoso_has_cuidador_idoso`
    FOREIGN KEY (`idoso_idoso_id`)
    REFERENCES `cuide`.`idoso` (`idoso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idoso_has_cuidador_cuidador1`
    FOREIGN KEY (`cuidador_cuidador_id`)
    REFERENCES `cuide`.`cuidador` (`cuidador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
